#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6504491690 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: vn # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link:
  https://play.google.com/store/apps/details?id=todoapp.syncplanner.reminders
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Quizzes - Trắc Nghiệm là ứng dụng dành cho những người yêu thích thử thách trí tuệ và khám phá kiến thức. Với hàng loạt câu hỏi đa dạng thuộc nhiều chủ đề như Nghệ thuật & Văn học, Khoa học, Địa lý, Công nghệ, và cả Văn hóa đại chúng, bạn sẽ luôn tìm thấy điều thú vị để học hỏi.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Nguyễn Đức Hoàng Phi
your_city: Nha Trang
email_address: nguyenduchoangphi922016@gmail.com
facebook_username: hoangfree
github_username: phiahihi
your_link: https://my-portfolio.store/

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Trải nghiệm đa dạng chủ đề
    description: Khám phá hàng ngàn câu hỏi trắc nghiệm thuộc nhiều chủ đề như Nghệ thuật, Khoa học, Lịch sử, Công nghệ, và Văn hóa đại chúng. Chọn chủ đề yêu thích hoặc thử sức ở lĩnh vực mới!
    fontawesome_icon_name: layer-group

  - title: Chơi và nhận phần thưởng
    description: Trả lời đúng để nhận điểm số, xu thưởng và các phần thưởng độc quyền. Thách đấu bạn bè và chinh phục bảng xếp hạng!
    fontawesome_icon_name: trophy

  - title: Giao diện thân thiện, dễ sử dụng
    description: Ứng dụng được thiết kế trực quan với hình ảnh và màu sắc sinh động, mang lại trải nghiệm học hỏi thú vị và lôi cuốn.
    fontawesome_icon_name: palette

  - title: Cập nhật câu hỏi thường xuyên
    description: Câu hỏi mới được cập nhật hàng tuần, đảm bảo nội dung luôn phong phú và phù hợp với mọi đối tượng người chơi.
    fontawesome_icon_name: sync-alt

  - title: Hỗ trợ đa nền tảng
    description: Dễ dàng truy cập ứng dụng trên mọi thiết bị, từ điện thoại di động đến máy tính bảng, với tốc độ mượt mà và ổn định.
    fontawesome_icon_name: mobile-alt

  - title: Bảng Xếp Hạng
    description: So tài cùng bạn bè và hàng ngàn người chơi khác trên bảng xếp hạng. Thể hiện kiến thức và giành vị trí cao nhất để nhận những phần thưởng đặc biệt!
    fontawesome_icon_name: chart-line

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
